In [3]:
import sqlite3
import pandas as pd

In [12]:
with sqlite3.connect('data/chinook.db') as connection:
    df_customers = pd.read_sql(
        "select * from customers",
        con=connection
    )

df_customers.head(10)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4

In [13]:
df_iris = pd.read_json('data/iris.json')
df_iris.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [7]:
df_iris.shape

(150, 5)

In [8]:
df_iris.dtypes

sepalLength    float64
sepalWidth     float64
petalLength    float64
petalWidth     float64
species            str
dtype: object

In [10]:
df_iris.columns

Index(['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species'], dtype='str')

In [11]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [21]:
df_titanic = pd.read_excel('data/titanic.xlsx')
df_titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
!pip install pyarrow
!pip install fastparquet

Collecting pyarrow
  Using cached pyarrow-23.0.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (3.0 kB)
Using cached pyarrow-23.0.0-cp313-cp313-macosx_12_0_arm64.whl (34.2 MB)
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.0
Requirement already satisfied: fastparquet in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2025.12.0)
Requirement already satisfied: pandas>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from fastparquet) (3.0.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from fastparquet) (2.4.2)
Requirement already satisfied: cramjam>=2.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from fastparquet) (2026.2.0)
Requirement already satisfied: packaging in /Users/macbook/Library/Python/3.13/lib/python/site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/macbook/Library/Python/3.13/lib/python/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/macbook/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)

In [6]:
userdata = pd.read_parquet('data/userdata.parquet', engine="pyarrow")

In [8]:
userdata.info

<bound method DataFrame.info of       registration_dttm    id first_name last_name                     email  \
0   2016-02-03 07:55:29     1     Amanda    Jordan          ajordan0@com.com
1   2016-02-03 17:04:03     2     Albert   Freeman           afreeman1@is.gd
2   2016-02-03 01:09:31     3     Evelyn    Morgan   emorgan2@altervista.org
3   2016-02-03 00:36:21     4     Denise     Riley          driley3@gmpg.org
4   2016-02-03 05:05:31     5     Carlos     Burns  cburns4@miitbeian.gov.cn
..                  ...   ...        ...       ...                       ...
995 2016-02-03 10:30:59   996     Dennis    Harris      dharrisrn@eepurl.com
996 2016-02-03 17:16:53   997     Gloria  Hamilton    ghamiltonro@rambler.ru
997 2016-02-03 05:02:20   998      Nancy    Morris         nmorrisrp@ask.com
998 2016-02-03 02:41:32   999      Annie   Daniels    adanielsrq@squidoo.com
999 2016-02-03 09:52:18  1000      Julie     Meyer       jmeyerrr@flavors.me

     gender       ip_address                cc       country  birthdate  \
0    Female      1.197.201.2  6759521864920116     Indonesia   3/8/1971
1      Male   218.111.175.34                          Canada  1/16/1968
2    Female     7.161.136.94  6767119071901597        Russia   2/1/1960
3    Female    140.35.109.83  3576031598965625         China   4/8/1997
4             169.113.235.40  5602256255204850  South Africa
..      ...              ...               ...           ...        ...
995    Male  178.180.111.236   374288806662929        Greece   7/8/1965
996  Female     71.50.39.137                           China  4/22/1975
997            6.188.121.221  3553564071014997        Sweden   5/1/1979
998  Female    97.221.132.35    30424803513734         China  10/9/1991
999  Female    217.1.147.132   374288099198540         China

        salary                   title comments
0     49756.53        Internal Auditor    1E+02
1    150280.17           Accountant IV
2    144972.51     Structural Engineer
3     90263.05  Senior Cost Accountant
4          NaN
..         ...                     ...      ...
995  263399.54                  Editor
996   83183.54   VP Product Management
997        NaN        Junior Executive
998   18433.85                  Editor        ​
999  222561.13

[1000 rows x 13 columns]>

In [9]:
df_movie = pd.read_csv('data/movie.csv')

In [10]:
df_movie.sample(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4817,Black and White,Deborah Anderson,16.0,66.0,4.0,232.0,Jesse Jane,502.0,NaN,Documentary,...,9.0,English,USA,NaN,150000.0,2013.0,366.0,5.3,NaN,207
1520,Color,Mike Newell,56.0,124.0,179.0,551.0,Kurt Fuller,11000.0,8406264.0,Comedy|Drama|Romance,...,175.0,English,USA,R,38000000.0,1999.0,617.0,6.0,2.35,783
1080,Color,Stephen Norrington,184.0,110.0,45.0,595.0,Traci Lords,886.0,70001065.0,Action|Horror,...,582.0,English,USA,R,45000000.0,1998.0,650.0,7.1,2.35,0
4605,Color,Thomas Lilti,18.0,102.0,12.0,2.0,Félix Moati,541.0,NaN,Comedy|Drama,...,1.0,French,France,NaN,NaN,2016.0,8.0,7.2,NaN,36
2308,Color,Kevin Reynolds,9.0,107.0,58.0,324.0,Jason Scott Lee,699.0,305070.0,Action|Adventure|Drama|History|Romance,...,25.0,English,USA,R,20000000.0,1994.0,533.0,6.4,2.35,399
1982,Color,Atom Egoyan,97.0,107.0,460.0,490.0,Alison Lohman,14000.0,871527.0,Crime|Drama|Mystery|Thriller,...,128.0,English,Canada,R,25000000.0,2005.0,1000.0,6.5,2.35,507
359,Color,Ben Stiller,308.0,121.0,0.0,918.0,Steve Coogan,21000.0,110416702.0,Action|Comedy,...,577.0,English,USA,R,92000000.0,2008.0,1000.0,7.0,2.35,0
4309,Color,Larry Clark,71.0,91.0,184.0,82.0,Leo Fitzpatrick,3000.0,7417210.0,Drama,...,408.0,English,USA,NaN,1500000.0,1995.0,202.0,7.0,1.85,0
3122,Color,François Girard,94.0,130.0,63.0,2.0,Clotilde Mollet,24.0,9473382.0,Drama|Music|Mystery|Romance,...,247.0,French,Canada,R,10000000.0,1998.0,3.0,7.7,1.85,0
2833,Color,Patrice Leconte,61.0,112.0,83.0,8.0,Daniel Auteuil,2000.0,3058380.0,Drama|Romance,...,69.0,French,France,R,100000000.0,2000.0,370.0,7.3,2.35,186

In [14]:
df_iris

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [19]:
df_iris.columns = [column.lower() for column in df_iris.columns]
df_iris[['sepallength', 'sepalwidth']]

     sepallength  sepalwidth
0            5.1         3.5
1            4.9         3.0
2            4.7         3.2
3            4.6         3.1
4            5.0         3.6
..           ...         ...
145          6.7         3.0
146          6.3         2.5
147          6.5         3.0
148          6.2         3.4
149          5.9         3.0

[150 rows x 2 columns]

In [24]:
df_titanic[df_titanic['Age'] > 30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
df_titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [27]:
userdata[["first_name", 'gender']]

    first_name  gender
0       Amanda  Female
1       Albert    Male
2       Evelyn  Female
3       Denise  Female
4       Carlos
..         ...     ...
995     Dennis    Male
996     Gloria  Female
997      Nancy
998      Annie  Female
999      Julie  Female

[1000 rows x 2 columns]

In [ ]:
set(userdata['country'])

{'"Bonaire',
 'Afghanistan',
 'Aland Islands',
 'Albania',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Azerbaijan',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Bermuda',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chile',
 'China',
 'Colombia',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of the Congo',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Ethiopia',
 'Faroe Islands',
 'Finland',
 'France',
 'Gambia',
 'Georgia',
 'Germany',
 'Greece',
 'Guatemala',
 'Guinea',
 'Haiti',
 'Honduras',
 'Indonesia',
 'Iran',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Japan',
 'Kazakhstan',
 'Kiribati',
 'Laos',
 'Latvia',
 'Lebanon',
 'Liberia',
 'Libya',
 'Luxembourg',
 'Macedonia',
 'Malaysia',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'Nicaragua',
 'Nigeria',
 'Norfolk Island',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestinian Territory',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Russia',
 'Saudi Arabia',
 'Serbia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Sweden',
 'Tanzania',
 'Thailand',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe'}

In [34]:
len(set(userdata['country']))

120

In [33]:
userdata[userdata["country"] == 'Uzbekistan']

,registration_dttm,id,first_name,last_name,email,gender,ip_address,cc,country,birthdate,salary,title,comments
775,2016-02-03 07:18:39,776,Craig,Myers,cmyerslj@google.cn,Male,133.209.184.64,6759194371556839,Uzbekistan,10/28/1973,253657.82,Help Desk Technician,

In [38]:
filtered = df_movie[df_movie['duration'] > 120]
filtered

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4674,Color,Kay Pollak,34.0,133.0,10.0,19.0,Frida Hallgren,690.0,9910.0,Comedy|Drama|Music|Romance,...,94.0,Swedish,Sweden,NaN,25000000.0,2004.0,24.0,7.6,1.85,0
4695,Black and White,D.W. Griffith,69.0,123.0,204.0,9.0,Mae Marsh,436.0,NaN,Drama|History|War,...,88.0,NaN,USA,Not Rated,385907.0,1916.0,22.0,8.0,1.33,691
4767,Black and White,King Vidor,48.0,151.0,54.0,6.0,Renée Adorée,81.0,NaN,Drama|Romance|War,...,45.0,NaN,USA,Not Rated,245000.0,1925.0,12.0,8.3,1.33,226
4792,Black and White,Carl Theodor Dreyer,54.0,126.0,147.0,0.0,Sylvia Eckhausen,0.0,NaN,Drama|Fantasy,...,49.0,Danish,Denmark,Not Rated,NaN,1955.0,0.0,8.1,1.37,863
4893,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33

In [40]:
filtered['director_facebook_likes'].sort_values(ascending=False)

96      22000.0
97      22000.0
3       22000.0
66      22000.0
1222    22000.0
         ...
3357        NaN
3582        NaN
3799        NaN
4005        NaN
4031        NaN
Name: director_facebook_likes, Length: 1039, dtype: float64

In [41]:
df_iris

     sepallength  sepalwidth  petallength  petalwidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [43]:
df_iris.describe()

       sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.057333     3.758000    1.199333
std       0.828066    0.435866     1.765298    0.762238
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [44]:
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [45]:
df_titanic['Age'].min()

np.float64(0.42)

In [46]:
df_titanic['Age'].max()

np.float64(80.0)

In [48]:
df_titanic['Age'].sum()

np.float64(21205.17)

In [49]:
df_movie[df_movie['director_facebook_likes'] == df_movie['director_facebook_likes'].max()]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3603,Color,Joseph Gordon-Levitt,364.0,90.0,23000.0,694.0,Scarlett Johansson,23000.0,24475193.0,Comedy|Drama|Romance,...,314.0,English,USA,R,3000000.0,2013.0,19000.0,6.6,2.35,33000

In [54]:
df_movie[['duration', 'director_name', 'actor_2_name']].sort_values(by='duration', ascending=False).head(5)

      duration        director_name              actor_2_name
1694     511.0                  NaN  Ingvar Eggert Sigurðsson
2436     334.0                  NaN      Nora von Waldstätten
1487     330.0      Taylor Hackford             Jesse Borrego
1134     325.0       Michael Cimino             Sam Waterston
3254     300.0  Chatrichalerm Yukol      Chatchai Plengpanich

In [55]:
df_movie.nlargest(5, 'duration')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1694,Color,NaN,16.0,511.0,NaN,51.0,Ingvar Eggert Sigurðsson,147.0,NaN,Crime|Drama|Thriller,...,19.0,Icelandic,Iceland,NaN,NaN,NaN,63.0,8.2,16.00,0
2436,Color,NaN,108.0,334.0,NaN,30.0,Nora von Waldstätten,897.0,145118.0,Biography|Crime|Drama|Thriller,...,36.0,English,France,Not Rated,NaN,NaN,30.0,7.7,2.35,0
1487,Color,Taylor Hackford,12.0,330.0,138.0,672.0,Jesse Borrego,848.0,4496583.0,Crime|Drama,...,129.0,English,USA,R,35000000.0,1993.0,674.0,8.0,1.66,6000
1134,Color,Michael Cimino,102.0,325.0,517.0,678.0,Sam Waterston,12000.0,1500000.0,Adventure|Drama|Western,...,189.0,English,USA,R,44000000.0,1980.0,849.0,6.8,2.35,1000
3254,Color,Chatrichalerm Yukol,31.0,300.0,6.0,6.0,Chatchai Plengpanich,7.0,454255.0,Action|Adventure|Drama|History|War,...,47.0,Thai,Thailand,R,400000000.0,2001.0,6.0,6.6,1.85,124

In [57]:
userdata.isna().sum()

registration_dttm     0
id                    0
first_name            0
last_name             0
email                 0
gender                0
ip_address            0
cc                    0
country               0
birthdate             0
salary               68
title                 0
comments              6
dtype: int64

In [62]:
userdata['comments'].isna().fillna(userdata['salary'].mean()).sum()

np.int64(6)

In [63]:
userdata['salary'].isna().fillna(userdata['salary'].mean()).sum()

np.int64(68)