In [8]:
import pandas as pd
import numpy as np
import json

In [9]:
df = pd.read_csv('super_dirty_students.csv')
copydf = df.copy()

In [12]:
import json
import ast

def safe_parse(x):
    try:
        return ast.literal_eval(x)
    except:
        return {}

df['profile_json'] = df['profile_json'].apply(safe_parse)

# print(df['profile_json'])
df['hobbies'] = df['profile_json'].apply(lambda x: x.get('hobbies'))
df['skills'] = df['profile_json'].apply(lambda x: x.get('skills'))
df['family'] = df['profile_json'].apply(lambda x: x.get('family'))
df['devices'] = df['profile_json'].apply(lambda x: x.get('devices'))
df[['hobbies', 'skills', 'family', 'devices']].head()

  hobbies skills family devices
0    None   None   None    None
1    None   None   None    None
2    None   None   None    None
3    None   None   None    None
4    None   None   None    None

In [11]:
df[['hobbies', 'skills', 'family', 'devices']].head()

,hobbies,skills,family,devices
0,"[gun, nice]","{'tech': {'python': 2, 'excel': 5, 'sql': 1}, ...","{'siblings': 4, 'income': {'father': 1198, 'mo...","[{'type': 'laptop', 'brand': 'HP', 'year': 202..."
1,None,None,None,None
2,"[fast, clearly]","{'tech': {'python': 5, 'excel': 3, 'sql': 1}, ...","{'siblings': 1, 'income': {'father': 263, 'mot...","[{'type': 'laptop', 'brand': 'HP', 'year': 202..."
3,"[left, role]","{'tech': {'python': 3, 'excel': 5, 'sql': 1}, ...","{'siblings': 4, 'income': {'father': 508, 'mot...","[{'type': 'laptop', 'brand': 'Lenovo', 'year':..."
4,"[sort, science]","{'tech': {'python': 1, 'excel': 4, 'sql': 1}, ...","{'siblings': 3, 'income': {'father': 862, 'mot...","[{'type': 'laptop', 'brand': 'Lenovo', 'year':..."